README.md
Additional sections copied from the biogo readme.
Omitted the following line from the Library Structure and Coding Style section:
The bíogo library structure is influenced both by the Go core library.
=> Update README.md install command

bgzf/index/index.go, bgzf/index/index_test.go
No tests. The test needs to come, but it requires engineering a set of blocks and index chunks to mimic the output shown in #10.
=> bgzf/index: fix chunk reader iteration

bgzf/index/index.go, bgzf/index/index_test.go, bgzf/reader.go
=> bgzf,bgzf/index: prevent ChunkReader overreading when an end is at block offset 0

sam/cigar.go, sam/sam_test.go
When parsing SA tags or MD, we may also need to know the length often
the chimeric alignment or determine the length of the Cigar. With this
change, it is possible to do so without replicating code in Record.End()
I'm not sure RefLen() is the best name...
=> Add Cigar.RefLen()

sam/auxtags.go, sam/record.go
Record.Tag() is showing up in my profiling. This drastically reduces the time spent there:
The time for the code below gives:
```
benchmark            old ns/op     new ns/op     delta
BenchmarkStats-4     28.0          7.36          -73.71%
benchmark            old allocs     new allocs     delta
BenchmarkStats-4     0              0              +0.00%
benchmark            old bytes     new bytes     delta
BenchmarkStats-4     0             0             +0.00%
```
```Go
package main
import (
"log"
"testing"
"github.com/biogo/hts/sam"
)
func main() {
}
func mustAux(a sam.Aux, err error) sam.Aux {
if err != nil {
panic(err)
}
return a
}
func BenchmarkStats(b *testing.B) {
r := &sam.Record{
AuxFields: []sam.Aux{
mustAux(sam.NewAux(sam.NewTag("NM"), "AAAAAAAAAAAAAAAA")), …
```
=> replace bytes.Compare with faster comparison for tag.

bam/bam_test.go, bam/reader.go, bgzf/reader.go
The last EOF-returned bgzf.Chunk troubles me - I don't really understand why it steps back by 4 bytes (and I don't have time to really resolve this). I have skirted the issue by saying that it's not valid. If you want to find out why this happens that would be great.
=> bam: fix EOF handling in Read

bam/reader.go
This was an experiment to see if it would improve bam parsing speed.
It replaces the smaller reads with a single, large read and then just works off the []byte.
With Omit(0) on an example bam, I get 15.5 seconds with this change and 18.3 on master.
With 3 cpus, I get 7.9 secs here and 11.3 master.
For Omit > 0, the difference, as expected is smaller, but still present.
The `TestConceptualBAM` test is failing. I'm not sure how to address that.
=> speed up bam.Read

bam/reader.go
this PR pre-allocates a slice of cap 3 when there are any Aux fields. 
Comparing to the commit in #42:
```
name    old time/op    new time/op    delta
Read-4    5.81ms ± 1%    5.48ms ± 1%   -5.59%  (p=0.008 n=5+5)
name    old alloc/op   new alloc/op   delta
Read-4    4.86MB ± 0%    4.25MB ± 0%  -12.60%  (p=0.008 n=5+5)
name    old allocs/op  new allocs/op  delta
Read-4     29.9k ± 0%     24.6k ± 0%  -17.68%  (p=0.008 n=5+5)
```
and comparing on the same bam with all tags removed:
```
name    old time/op    new time/op    delta
Read-4    3.29ms ± 1%    3.32ms ± 2%   ~     (p=0.548 n=5+5)
name    old alloc/op   new alloc/op   delta
Read-4    1.96MB ± 0%    1.96MB ± 0%   ~     (p=0.421 n=5+5)
name    old allocs/op  new allocs/op  delta
Read-4     16.5k ± 0%     16.5k ± 0%   ~     (p=0.349 …
```
=> Aux allocate

bam/reader.go
Looking at parseAux, I think we should make that return an error rather than panicking, and be more forgiving with indexing errors. At the moment it's brittle for badly formed bam files.
=> bam: protect aux tags from append overwrites by user

bam/reader.go
Previously an empty chunks parameter would result in a complete iteration over the bam. Now we prime the iterator as having completed when there is no chunk to iterate over.
=> bam: handle empty chunks during iterator creation

bgzf/bgzf_test.go, bgzf/cache.go
This handles both 1.8 compress/gzip behaviour and pre-1.8 behaviour.
Also fix incorrect test error report value.
Fixes #50.
=> bgzf: fix magic block detection

bam/bam_test.go, internal/index_read.go
gives about a 1.5-4X speed improvement in bam.ReadIndex, depending
on the index.
=> internal/index: batch calls to binary.Read to limit reflection overhead

paper/examples/flagstat/README.md, paper/examples/flagstat/flagstat.go
This is a harsher benchmark and one that is used across implementations. We come out worse, but it is more realistic a test of use (the performance drop is likely due to the fact that GC becomes more of an issue for a long run). The change also makes the Go program a workalike to make comparison more convincing and simplifies some of the logic - we are still doing work that is unnecessary, but fixing that makes it more complicated.
=> paper/examples/flagstat: use heavier benchmark and match logic

tabix/tabix.go
A user was having a problem with vcfanno (brentp/vcfanno#57 ) on a bed file with a large number of references.
This change fixes.
=> tabix: replace Read with io.ReadFull

sam/auxtags.go, sam/sam_test.go
update #89
change on (newly added) aux parsing benchmark:
```
name        old time/op    new time/op    delta
ParseAux-4     661ns ± 3%     256ns ± 1%  -61.20%  (p=0.000 n=8+10)
name        old alloc/op   new alloc/op   delta
ParseAux-4      376B ± 0%      128B ± 0%  -65.96%  (p=0.000 n=10+10)
name        old allocs/op  new allocs/op  delta
ParseAux-4      12.0 ± 0%       7.0 ± 0%  -41.67%  (p=0.000 n=10+10)
```
=> sam: optimize ParseAux

bgzf/bgzf_test.go, bgzf/writer.go
This is submitted with contrition. I had thought compress/gzip defaulted to the zero byte. This is not true; I was clobbering the 0xff value it has by default (since 2012!).
=> bgzf: set default OS to unknown

sam/record.go
@brentp @yipal Please take a look.
Fixes #104.
=> sam: make zero length CIGAR or unmapped reads have unit length

bgzf/bgzf.go, bgzf/bgzf_test.go, bgzf/reader.go
Found by go-fuzz, hinted at by #108.
I re-ran the bgzf go-fuzz code at the issue above and can more simply fix the errors by handling the zero and negative needed limited read cases.
I am not entirely sure of the zero-size case. I suspect that the `io.EOF` should be revised to a `nil` error after it has been intercepted after `d.readMember` returns in `decompressor.nextBlockAt`, but I would prefer this failure to the panic that exists, though please have a think about that.
I think the fuzzing has saturated, but I'll leave it running for a while.
=> bgzf: fix block size handling errors

bam/bam_test.go, bam/reader.go
This fixes a couple of bounds errors found by go-fuzz, and extrapolates to another. The code is safer from other perspectives and also a little less horrible in its use of unsafe. I suspect there may be performance improvements from some of the changes as well.
=> bam: fix various bounds checks

bam/writer.go
Fixes defect found in #132 more simply.
/cc @bsipos
=> bam: fix qual encoding length for nil qualities

bam/reader.go
=> bam: prevent -1 becoming positive in conversion to int

bam/bam_test.go, bam/reader.go
Previous test was skipped. The `n` incrementing now checks that ieration actually occurs.
=> bam: iterate over file when no chunks are given

bam/reader.go
The only remaining area of optimisation is in decoding headers for the allocation of `text`, but there only pooled buffers are possible. I tried this using the system in #156 and it had no impact either way.
=> bam: use heuristics to reduce reallocation

bgzf/bgzf_test.go, bgzf/cache.go, bgzf/line_example_test.go, bgzf/reader.go
This allows more efficient indexing of tabix formatted or other line-based data.
=> bgzf: satisfy io.ByteReader

bgzf/bgzf_test.go
Due to https://github.com/golang/go/issues/51417
Go1.19 also returns io.ErrUnexpectedEOF for invalid gzip input.
=> bgzf: fix test with go1.19
