biogo/hts

bgzf/index/index.go
bgzf/index/index_test.go

bgzf/index: fix repeat reading

---

csi/csi_read.go
csi/csi_write.go
tabix/tabix.go

tabix,csi: harmonise api and reduce stutter

---

bam/bam_test.go
bgzf/index/index.go
internal/index.go
tabix/tabix.go

bgzf/index: export errors

---

bam/writer.go
sam/record.go

bam,sam: update and add name length checks

---

sam/header.go
sam/parse_header.go
sam/program.go
sam/read_group.go
sam/reference.go
sam/sam_test.go

I ended up going with the othertags approach. The publicly visible map turned out to be a lot more complicated.

sam: fix HD line parsing for cases where tags are user defined

---

sam/auxtags.go
sam/sam_test.go

sam: fix f type parsing

---

bam/bam_test.go
bam/reader.go
sam/auxtags.go

Fixes #30.
@brentp Please take a look. The time saving is pretty good, but I'm not sure that the API complexity addition and code growth is worth it, so I'd appreciate your view.

bam: add capacity to read reduced complexity records faster

---

sam/parse_header.go
sam/sam_test.go

Also add test for program unique IDs.

sam: fix RG namespace separation

---

sam/record.go
sam/sam_test.go

You may want to check your PR against what's happening here too.

sam: simplify and fix end behaviour

---

bam/reader.go

bam: minor doc and error case fixups

---

bam/reader.go

this gives about a 2.5% speed bump.
```
benchmark           old ns/op     new ns/op     delta
BenchmarkRead-4     6454267       6272807       -2.81%
benchmark           old allocs     new allocs     delta
BenchmarkRead-4     34020          30684          -9.81%
```

re-use the [4]byte for getting blocksize.

---

sam/auxtags.go
sam/sam_test.go

I don't know how this went unnoticed for so long.

sam: fix integer range and binary Aux encodings

---

bgzf/bgzf_test.go
bgzf/go1_8_test.go
bgzf/writer.go

bgzf: describe issues with tabix header checks

---

codemeta.json
paper/paper.md

NOT FOR SUBMISSION
@brentp @dadelson Please take a look.
This will be merged after #58 is decided one way or another, and a v1.0.0 tag has been added to the repo.

publish: add JOSS paper and metadata

---

bgzf/writer.go

See https://github.com/samtools/htslib/commit/ec1d68e23ce75c7040ec895dfc0fffb1a2acb22c for rationale.

bgzf: update spec compliance warning

---

paper/paper.md

Addresses some of https://github.com/openjournals/joss-reviews/issues/157#issuecomment-274406225

paper: extend summary to include citations

---

README.md
codemeta.json

@sb10 @brentp  Please take a look.
Closes #65.

README: add summary, example and community guidelines

---

paper/examples/flagstat/README.md

@brentp @sb10 Please take a look.
Closes #69.

paper/examples/flagstat: add multithreaded samtools

---

paper/paper.bib
paper/paper.md

@brentp @arfon Please take a look.
Addresses https://github.com/openjournals/joss-reviews/issues/168#issuecomment-277406661

paper: properly mark up references

---

sam/parse_header.go

sam: make zero value for Header UnmarshalText without panicking

---

sam/auxtags.go

This makes no functional difference, but improves user and developer documentation. Not adding aux tag list.
Fixes #78.

sam: update tags list and docs

---

bam/bam_test.go
sam/header.go
sam/parse_header.go
sam/program.go
sam/read_group.go
sam/reference.go
sam/sam_test.go

sam: allow Reference, ReadGroup and Program renames

---

sam/HG00096_1000_test.go
sam/header.go

sam: fix ownership maintainance during Header cloning

---

README.md

README: fix markdown

---

bam/merger.go
bam/merger_example_test.go
bam/merger_test.go
sam/header.go
sam/program.go
sam/read_group.go
sam/record.go
sam/reference.go
sam/sam_test.go

@brentp @dongweigogo Please take a look.
Fixes #77.

bam,sam: add merging functions

---

bam/merger.go
bam/merger_example_test.go
bam/merger_test.go
sam/header.go

@brentp @dongweigogo Please take a look.
Fixes #94.

bam: fix merger for short bams

---

bgzf/reader.go

bgzf: make Close wait on worker completion

---

sam/parse_header.go
sam/read_group.go
sam/sam_test.go

@Defgenx Please try this change.

sam: conform more closely to ISO8601

---

sam/record.go

sam: fix bin calculation for unmapped reads with mapped mates

---

sam/record.go

This change upsets me, but we should fit in with the behaviour of other tools in the ecosystem, I guess.

sam: reflect the behaviour of other tools

---

sam/parse_header.go
sam/sam_test.go

sam: extend support range for ISO8601

---

csi/csi.go

csi: don't break early when selecting chunks 

---

sam/cigar.go
sam/sam_test.go

@brentp @nathanhaigh Please take a look.

sam: handle CIGAR operations longer than 1<<28-1 more gracefully

---

bam/writer.go

They were found by errcheck.  As for errWriter / binaryWriter, this change
merges the two types and changes write* methods not to return any error. Writing
to bytes.Buffer is guaranteed to be error free.

hts: Address unchecked-error warnings

---

sam/record.go
sam/sam_test.go

@bsipos Please take a look.
Would you try this with your code? If you can provide a simple reproducer, I will include that in a test here.
Fixes #133.

sam: don't compare query length to template length in validation

---

CONTRIBUTING.md
THIRD_PARTY_LICENSES/Gonum-LICENSE

This is a more detailed contribution guidelines document (derived extensively from the Gonum document - hence the third party license addition).

docs: add CONTRIBUTING.md

---

sam/record.go

sam: simplify docs

---

.github/FUNDING.yml

FUNDING: set up sponsorship button
